training_pipeline_config:
  pipeline_name: supply_chain_
  artifact_dir: artifact

data_ingestion_config:
  raw_data_dir: raw_data
  ingested_dir: ingested_data
  ingested_train_dir: train
  ingested_test_dir: test